### PR TITLE
feat: customizable events

### PR DESCRIPTION
**Pull request by tomosterlund**
## Checklist

Please put "X" in the below checkboxes that apply::

- [ ] If committing a bugfix, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [ ] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [X] If committing a new feature, I have also written an appropriate test suite for it. 

I have tested the following:  

- [X] Qalendar component in month mode. 
- [X] Qalendar component in week mode. 
- [X] Qalendar component in day mode. 
- [X] Day mode on emulated mobile. 
- [X] Dragging and dropping events. 
- [X] Resizing events in day/week modes. 
- [X] Clicking events to open event dialog. 

## This PR solves the following problem. 

This PR adds one of the features in this feature request: https://github.com/tomosterlund/qalendar/issues/50

The implementer should be able to:
1. Take full control over the looks of an event through scoped, named slots.
2. Take (almost) full control over the appearance of the event dialog, that opens upon clicking an event.

Apart from the above features, this PR also adds the configuration option `disableModes`.

## How to test this PR. 

1. Start dev server and go to http://localhost:3000/#/cypress/customized-events
2. Test that the above two features work.
3. Run `npm run docs:dev` to view the new documentation for the features, and see if anything needs to be clarified for any developers wanting to use these features.

### CODE REVIEW

**Comment by tomosterlund** [comment]
@felix-berlin for turning all events on the url above to custom events, you need to change this line:

`if (i % 2 === 0) e.isCustom = true;`

to just:

`e.isCustom = true;`

Forgot to delete it before pushing ^^

**Comment by tomosterlund** [comment]
Pushed a bunch of attempts at fixing a build error, for anyone using the slots in TS. Not critical however, because there are workarounds, so I will give it up for now, and open a new branch where I will fix this later.

Important however, that we merge this branch with "Squash and merge" when testing is done, since I spammed it with a few not so valuable commits.

**Comment by felix-berlin** [comment]
Hey Tom,
I'm done with testing. Looks pretty good to me 💪

I also changed the release workflow trigger to "push on master". I think it's not necessary to run the workflow on pull request.

**Review by felix-berlin — APPROVED** [review]
Looks good to me

**Comment by tomosterlund** [comment]
Cool! Thanks 🙏I’ll merge later today then. Might need to undo a couple of changes on the type declarations I pushed

**Pull request merged**
