### PR TITLE
Translate Dropdpown menu to Frensh

### PR DESCRIPTION
**Pull request by maha-oueghlani**
## Checklist

Please put "X" in the below checkboxes that apply::

- [ ] If committing a bugfix, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [x] If committing a new feature, I have also written an appropriate test suite for it. 

I have tested the following:  

- [X] Qalendar component in month mode. 
- [X] Qalendar component in week mode. 
- [X] Qalendar component in day mode. 
- [X] All of the above modes on emulated mobile view. 
- [ ] Dragging and dropping events. 
- [ ] Resizing events in day/week modes. 
- [ ] Clicking events to open event dialog. 

## This PR solves the following problem**. 

Translate dropdown menu to frensh.

## How to test this PR**. 

1. `npm run dev`
2. change language in DevToolbar to "fr-FR"
3. dropdown of representation mode change like this 
fr-FR

**Notes**

- I didn't test effects on events because changes are not specific to events.
- I'm not familiar with git that's why I revert the first commit, I thought that I did a mistake. But it's all good in the last commit.

### CODE REVIEW

**Comment by tomosterlund** [comment]
Hello there. Thank you very much for this contribution. We appreciate you taking the time to improve this library!

I started the Github actions, and will check in later for a quick review

**Comment by tomosterlund** [comment]
I'll go ahead and merge this, and trust the Deepl-Translation for the last key. Thanks again for contributing!

**Comment by maha-oueghlani** [comment]
OK thank's for the merge. Sorry I didn't present on Github last period thats why I didn't answer you regarding the last key. But anyway it's correct :)

**Pull request merged**
