### PR TITLE
Stylelint

### PR DESCRIPTION
**Pull request by felix-berlin**
- Add Stylelint + config
- Fix Stylelint Errors

### CODE REVIEW

**Comment by tomosterlund** [comment]
Detected one problem on the branch. Will keep looking a little, but here's a screenshot.

Bildschirmfoto 2022-08-05 um 23 41 24

- [ ] fix alignment of time in DayTimeline.vue

**Review by tomosterlund — CHANGES_REQUESTED** [review]
See comment and Screenshot in conversation. Let know if you need help :)

**Comment by felix-berlin** [comment]
> Detected one problem on the branch. Will keep looking a little, but here's a screenshot.
> 
> Bildschirmfoto 2022-08-05 um 23 41 24
> 
> * [ ]  fix alignment of time in DayTimeline.vue

Should be fixed with the last commit. The selector for this element was miss spelled ^^

**Comment by tomosterlund** [comment]
Did you also see the merge conflict? :)

**Comment by felix-berlin** [comment]
> Did you also see the merge conflict? :)

Jep, i seen it. I will solve it to day ☺️

**Comment by felix-berlin** [comment]
> Did you also see the merge conflict? :)

Managed to solve the conflict 😊

**Pull request merged**
